### ISSUE TITLE
[EPIC] Migrator Tool

### ISSUE THREAD

**Issue by pedrovalido** [Fujicracy/himalaya-migrators#1]
As discussed, we are going to start building the Himalaya migrator tool for Compound.

Initial Setup:
- [x] repo directory structure
- [x] Initial foundry setup
- [x] Hardhat setup (to test xChain operations)
- [x] linters and extra setup
- [x] install fuji-v2 repo as dependency

Next Steps:
- [x] interaction between connext - HimalayaBase - HimalayaCompound - CompoundV2/V3
- [x] script to deploy HimalayaConnext
- [ ] Adapt HimalayaCompound to each chain
- [x] initial test outbound V2 to V3 
- [x] initial test outbound V3 to V3
- [x] initial test inbound V2 to V3
- [x] initial test inbound V3 to V3
- [x] create tests for each chain
- [ ] create tests for each market
- [ ] Security aspects/brainstorm
- [ ] Documentations (comment code and build readME)

Note to self: we should also consider having bridge calldata if the migration.amount is 0. This is for cases where user wants to migrate only debt. Will payback debt on origin chain and bridge only a call to borrow on destination chain

**Comment by pedrovalido** [comment]
### Note to self
We should think about creating forge modules: 
- ILendingProvider (or modified version without view functions)
- CompoundV2 Lending provider implemented in fuji-v2 to inherit some of the functions instead of repeating them
- IFlasher and flasher implementations

**Comment by pedrovalido** [comment]
- Use hardhat with ts, not js
- Copy paste linters and extra from fuji-v2

**Comment by pedrovalido** [comment]
- first part of testing: move just collateral
- second part: move debt only if user repays it first

**Comment by pedrovalido** [comment]
Check permits and authorization. How is this handled in destination chain?

**Comment by pedrovalido** [comment]
@DaigaroCota With the new changes made to how we are testing I changes the todo list on the isse. 
Also added some important tasks :)

**Comment by pedrovalido** [comment]
Note to self:
Migrating a lending and borrow position:

- we assume the user has enough debt erc20 to payback the loan
- we pull funds from the user to payback
- we payback the users debt and then we do the rest

Missing tests with this (payback user debt)
