### ISSUE TITLE
[EPIC] Migrator Tool

### ISSUE THREAD

**Issue by pedrovalido** [Fujicracy/himalaya-migrators#2]
As discussed, we are going to start building the Himalaya migrator tool for Compound.

Trial:
- [ ] Spin up chain 1 locally
- [ ] Spin up chain 2 locally
- [ ] Deploy CompoundV2 in chain1
- [ ] Deploy CompoundV3 in chain2
- [ ] Open position in CompoundV2 chain1
- [ ] Open position in CompoundV3 chain2
- [ ] Migrate position from CompoundV2 chain1 to CompoundV3 chain2
